### ISSUE TITLE
Conflict with fastwiki plugin?

### ISSUE THREAD

**Issue by shallimus** [lupo49/dokuwiki-plugin-orphanswanted#31] opened 2017-03-24 19:15 UTC
With fastwiki disabled, clicking a "Backlinks" link on the page :wiki:wanted where I use the orphanswanted plugin brings me to a page showing me backlinks to the non-existent page :example:nonexistent:page

With fastwiki enabled, however, clicking the same link shows me backlinks to my Wanted page (:wiki:wanted). I noticed that clicking Back at this point takes me back to the page I was at _before_ I naviagated to :wiki:wanted, rather than back to :wiki:wanted as I would expect.

I suspect this may be fastwiki's fault, but does anyone have any insight into why this might be?

**Comment by jaller94** [comment] 2017-04-02 10:35
I am able to reproduce this.

Fastwiki loads some actions (`?do=`) via AJAX to speed up browsing. It looks like it cannot detect actions that refer to another page.

It is the fault of fastwiki as they do not support action links to other pages in general. I files an issue at zioth/dokuwiki_fastwiki#29.

Not sure how useful Fastwiki is without this being enabled, but you can disable the setting `plugin»fastwiki»fastpages` and it will be fixed.

**Comment by jaller94** [comment] 2017-04-02 14:50
@zioth correctly mentionied that this issue has not been resolved. Therefore, the issue should not have been closed.

I still don't see it as an incompatibility that should be fixed in this plugin but in fastwiki.

**Comment by zioth** [comment] 2017-04-02 23:18
I'll see if I can find time to fix this. Based on the description, it sounds like it's fastwiki's fault.

**Comment by shallimus** [comment] 2017-04-03 05:05
After a few days with FastWiki disabled, I'm not sure I see any significant speed difference, nor loss of essential functionality. The backlinks and diff links which were appearing broken now all work OK.

It's off-topic, but I wonder if FastWiki provides less benefit for a wiki which is only served over LAN and thus has a very fast and reliable connection to the server...?

**Comment by zioth** [comment] 2017-04-03 13:23
Fastwiki has the largest benefit on slower networks, in a shared hosting environment with low usage, or on a site with a large number of pages (the later two make the php cache that doku depends on nearly worthless). But even when I run my site on localhost, I see a noticeable difference if I turn on all the experimental features. Pre-loading links can make the site very fast if you have bandwidth to spare.

If your site is on a LAN, and you have a dedicated, fast server hosting the site, then the benefit of fastwiki is minimal, unless you use some of the experimental features. If people use your site over a VPN, they'll see a bigger difference.

**Comment by shallimus** [comment] 2017-04-03 14:08
Thanks zioth. Yes, my wiki is LAN-only, and is running a a moderately powerful VM. The bottleneck is likely to be CPU of my VM, rather than network bandwidth. It's not possible for anyone to access it from a machine not on the same network. I should be clear that while the issue described here might affect others more, it's not a show-stopper for me. I raised it mostly in case it helps someone else.

**Closed** 2019-01-03 04:52 UTC
