### ISSUE TITLE
Ignore links inside <code> tags

### ISSUE THREAD

**Issue by alandmoore** [lupo49/dokuwiki-plugin-orphanswanted#19] opened 2015-03-06 20:29 UTC
I've several pages that are templates or example codes which contain nonsense links inside code tags, e.g.

```
Make hyperlinks like this:
<code>
[[some-namespace:some-page]]
</code>
```

These links show up as "wanted" pages.

Ideally, I'd want the plugin to ignore any links inside a code block like this.

**Comment by jaller94** [comment] 2016-03-02 18:55
Can't reproduce with Detritus 2015-08-10a and orphanswanted 2012-12-05.

**Comment by jaller94** [comment] 2017-04-02 10:45
I'm closing this issue since I still cannot reproduce it. If someone is still affected by this I would like to see it being fixed.

**Closed by jaller94** 2017-04-02 10:45 UTC
Labels: can't reproduce
